### ISSUE TITLE
private repository on github

### ISSUE THREAD

**Issue by emmalovato** [ColumbiaJS/hw1#3]
Does our w3101hws repository need to be private like the readme for hw1 says, or could it also be public? I think you need a paid github subscription in order to create private repos which is why i'm asking!

**Comment by ohEmily** [comment]
Hey Emma,

At education.github.com you can request an education account as long you have a .edu email address as your primary email (go to Settings >> Emails). It will take a few days to a few weeks so it might be a little late for the homework.

We're supposed to have private repos because otherwise people could copy each other's work. If you still don't have a private repo, you might want to email the professor. You're right that buying a private repo costs a couple dollars.

-Emily

**Comment by emmalovato** [comment]
Ohhh, that makes sense! Thank you for the info, I'll email him and ask.

**Comment by beatrizfagundes** [comment]
Hi, Emma, could you please tell what the professor said about this question? Thanks in advance!
