### ISSUE TITLE
Clarification on 1st test for BallFollower

### ISSUE THREAD

**Issue by guribe94** [ColumbiaJS/hw1#7]
Hi, 
Could somebody please clarify what this test is actually testing:
"  1) BallFollower returns an object from the constructor function:
     AssertionError: expected undefined to equal 'firstSwap' "
Currently it is the only one of my tests that is failing but I don't actually understand what this means to fix it. According to this: http://stackoverflow.com/questions/9108925/how-is-almost-everything-in-javascript-an-object it seems that returning the position as a number (which is what I am doing) becomes an object because it is placed within an object wrapper. Is this not the case?
Thanks,
Gabe

**Comment by ng4biba** [comment]
I have the same problem. Everything in my code seems fine to me but somehow
I keep getting those errors. Maybe the exercise expect us to solve it in a
specific way.

Sent from my iPhone
On Jan 31, 2015, at 6:11 PM, guribe94 notifications@github.com wrote:

Hi,
Could somebody please clarify what this test is actually testing:
" 1) BallFollower returns an object from the constructor function:
AssertionError: expected undefined to equal 'firstSwap' "
Currently it is the only one of my tests that is failing but I don't
actually understand what this means to fix it. According to this:
http://stackoverflow.com/questions/9108925/how-is-almost-everything-in-javascript-an-object
it seems that returning the position as a number (which is what I am doing)
becomes an object because it is placed within an object wrapper. Is this
not the case?
Thanks,
Gabe

—
Reply to this email directly or view it on GitHub
https://github.com/ColumbiaJS/hw1/issues/7.

**Comment by levbrie** [comment]
@guribe94 @ng4biba Yes, that's correct.  Normally, the low-level implementation details are up to you, but because you're learning JavaScript for the first time, I want you to also learn how to recognize what is being expected of you in JavaScript terms.  In this case, the line:

``` js
expect(follower.start).to.equal('firstSwap');
```

means that I expect the BallFollower constructor function to return an object that has a `start` property as well as a `swap()` method.  The purpose of this property is to be able to get back the starting position of the ball at any point after the BallFollower is created.  Reopen this issue if you have any additional questions.
